import type { ModularPartType } from './types';

export interface ModularPartDefinition {
  type: ModularPartType;
  label: string;
  description: string;
  required: boolean;
  category: 'core' | 'attachment' | 'clothing' | 'accessory';
  socketId: string;
  parentSocketId: string | 'root';
  aliases: string[];
  boneHints: string[];
}

export const MODULAR_PART_CATALOG: ModularPartDefinition[] = [
  {
    type: 'head',
    label: 'Cabeza',
    description: 'Malla principal de la cabeza.',
    required: true,
    category: 'core',
    socketId: 'head_socket',
    parentSocketId: 'neck_socket',
    aliases: ['head', 'cabeza', 'face'],
    boneHints: ['Head', 'head', 'mixamorigHead'],
  },
  {
    type: 'neck',
    label: 'Cuello',
    description: 'Cuello o unión entre torso y cabeza.',
    required: true,
    category: 'core',
    socketId: 'neck_socket',
    parentSocketId: 'torso_socket',
    aliases: ['neck', 'cuello'],
    boneHints: ['Neck', 'neck', 'mixamorigNeck'],
  },
  {
    type: 'torso',
    label: 'Torso',
    description: 'Pecho, espalda y tronco principal.',
    required: true,
    category: 'core',
    socketId: 'torso_socket',
    parentSocketId: 'pelvis_socket',
    aliases: ['torso', 'chest', 'upperbody', 'spine', 'body'],
    boneHints: ['Spine', 'Chest', 'UpperChest'],
  },
  {
    type: 'left_arm',
    label: 'Brazo Izquierdo',
    description: 'Brazo superior izquierdo.',
    required: true,
    category: 'core',
    socketId: 'left_shoulder_socket',
    parentSocketId: 'torso_socket',
    aliases: ['leftarm', 'arm_l', 'upperarm_l', 'brazo_izquierdo', 'l_arm'],
    boneHints: ['LeftArm', 'Arm.L', 'mixamorigLeftArm'],
  },
  {
    type: 'right_arm',
    label: 'Brazo Derecho',
    description: 'Brazo superior derecho.',
    required: true,
    category: 'core',
    socketId: 'right_shoulder_socket',
    parentSocketId: 'torso_socket',
    aliases: ['rightarm', 'arm_r', 'upperarm_r', 'brazo_derecho', 'r_arm'],
    boneHints: ['RightArm', 'Arm.R', 'mixamorigRightArm'],
  },
  {
    type: 'left_forearm',
    label: 'Antebrazo Izquierdo',
    description: 'Antebrazo izquierdo.',
    required: true,
    category: 'core',
    socketId: 'left_elbow_socket',
    parentSocketId: 'left_shoulder_socket',
    aliases: ['leftforearm', 'forearm_l', 'lowerarm_l', 'antebrazo_izquierdo'],
    boneHints: ['LeftForeArm', 'Forearm.L', 'mixamorigLeftForeArm'],
  },
  {
    type: 'right_forearm',
    label: 'Antebrazo Derecho',
    description: 'Antebrazo derecho.',
    required: true,
    category: 'core',
    socketId: 'right_elbow_socket',
    parentSocketId: 'right_shoulder_socket',
    aliases: ['rightforearm', 'forearm_r', 'lowerarm_r', 'antebrazo_derecho'],
    boneHints: ['RightForeArm', 'Forearm.R', 'mixamorigRightForeArm'],
  },
  {
    type: 'left_hand',
    label: 'Mano Izquierda',
    description: 'Mano izquierda.',
    required: true,
    category: 'core',
    socketId: 'left_wrist_socket',
    parentSocketId: 'left_elbow_socket',
    aliases: ['lefthand', 'hand_l', 'mano_izquierda'],
    boneHints: ['LeftHand', 'Hand.L', 'mixamorigLeftHand'],
  },
  {
    type: 'right_hand',
    label: 'Mano Derecha',
    description: 'Mano derecha.',
    required: true,
    category: 'core',
    socketId: 'right_wrist_socket',
    parentSocketId: 'right_elbow_socket',
    aliases: ['righthand', 'hand_r', 'mano_derecha'],
    boneHints: ['RightHand', 'Hand.R', 'mixamorigRightHand'],
  },
  {
    type: 'pelvis',
    label: 'Pelvis',
    description: 'Pelvis o cadera base.',
    required: true,
    category: 'core',
    socketId: 'pelvis_socket',
    parentSocketId: 'root',
    aliases: ['pelvis', 'hips', 'hip', 'cadera'],
    boneHints: ['Hips', 'Pelvis', 'mixamorigHips'],
  },
  {
    type: 'left_leg',
    label: 'Pierna Izquierda',
    description: 'Muslo izquierdo.',
    required: true,
    category: 'core',
    socketId: 'left_hip_socket',
    parentSocketId: 'pelvis_socket',
    aliases: ['leftleg', 'upleg_l', 'thigh_l', 'pierna_izquierda'],
    boneHints: ['LeftUpLeg', 'Leg.L', 'mixamorigLeftUpLeg'],
  },
  {
    type: 'right_leg',
    label: 'Pierna Derecha',
    description: 'Muslo derecho.',
    required: true,
    category: 'core',
    socketId: 'right_hip_socket',
    parentSocketId: 'pelvis_socket',
    aliases: ['rightleg', 'upleg_r', 'thigh_r', 'pierna_derecha'],
    boneHints: ['RightUpLeg', 'Leg.R', 'mixamorigRightUpLeg'],
  },
  {
    type: 'left_calf',
    label: 'Pantorrilla Izquierda',
    description: 'Parte inferior de la pierna izquierda.',
    required: true,
    category: 'core',
    socketId: 'left_knee_socket',
    parentSocketId: 'left_hip_socket',
    aliases: ['leftcalf', 'calf_l', 'shin_l', 'pantorrilla_izquierda'],
    boneHints: ['LeftLeg', 'Shin.L', 'mixamorigLeftLeg'],
  },
  {
    type: 'right_calf',
    label: 'Pantorrilla Derecha',
    description: 'Parte inferior de la pierna derecha.',
    required: true,
    category: 'core',
    socketId: 'right_knee_socket',
    parentSocketId: 'right_hip_socket',
    aliases: ['rightcalf', 'calf_r', 'shin_r', 'pantorrilla_derecha'],
    boneHints: ['RightLeg', 'Shin.R', 'mixamorigRightLeg'],
  },
  {
    type: 'left_foot',
    label: 'Pie Izquierdo',
    description: 'Pie izquierdo.',
    required: true,
    category: 'core',
    socketId: 'left_ankle_socket',
    parentSocketId: 'left_knee_socket',
    aliases: ['leftfoot', 'foot_l', 'pie_izquierdo'],
    boneHints: ['LeftFoot', 'Foot.L', 'mixamorigLeftFoot'],
  },
  {
    type: 'right_foot',
    label: 'Pie Derecho',
    description: 'Pie derecho.',
    required: true,
    category: 'core',
    socketId: 'right_ankle_socket',
    parentSocketId: 'right_knee_socket',
    aliases: ['rightfoot', 'foot_r', 'pie_derecho'],
    boneHints: ['RightFoot', 'Foot.R', 'mixamorigRightFoot'],
  },
  {
    type: 'hair',
    label: 'Cabello',
    description: 'Cabello, mechones o peinados.',
    required: false,
    category: 'attachment',
    socketId: 'hair_socket',
    parentSocketId: 'head_socket',
    aliases: ['hair', 'cabello', 'fringe'],
    boneHints: ['Head', 'Hair'],
  },
  {
    type: 'helmet',
    label: 'Casco',
    description: 'Casco o armadura de cabeza.',
    required: false,
    category: 'attachment',
    socketId: 'helmet_socket',
    parentSocketId: 'head_socket',
    aliases: ['helmet', 'casco'],
    boneHints: ['Head'],
  },
  {
    type: 'glasses',
    label: 'Gafas',
    description: 'Lentes o gafas.',
    required: false,
    category: 'accessory',
    socketId: 'glasses_socket',
    parentSocketId: 'head_socket',
    aliases: ['glasses', 'gafas', 'eyewear'],
    boneHints: ['Head'],
  },
  {
    type: 'upper_clothing',
    label: 'Ropa Superior',
    description: 'Prendas de torso y pecho.',
    required: false,
    category: 'clothing',
    socketId: 'upper_clothing_socket',
    parentSocketId: 'torso_socket',
    aliases: ['shirt', 'hoodie', 'upper', 'top', 'ropa_superior'],
    boneHints: ['Spine', 'Chest'],
  },
  {
    type: 'lower_clothing',
    label: 'Ropa Inferior',
    description: 'Faldas, pantalones o prendas bajas.',
    required: false,
    category: 'clothing',
    socketId: 'lower_clothing_socket',
    parentSocketId: 'pelvis_socket',
    aliases: ['pants', 'skirt', 'lower', 'ropa_inferior'],
    boneHints: ['Hips', 'Pelvis'],
  },
  {
    type: 'shoulder_pads',
    label: 'Hombreras',
    description: 'Accesorios rígidos de hombro.',
    required: false,
    category: 'attachment',
    socketId: 'shoulder_pad_socket',
    parentSocketId: 'torso_socket',
    aliases: ['shoulderpad', 'shoulder_pads', 'hombreras'],
    boneHints: ['Shoulder.L', 'Shoulder.R'],
  },
  {
    type: 'gloves',
    label: 'Guantes',
    description: 'Guantes o cubiertas de mano.',
    required: false,
    category: 'clothing',
    socketId: 'glove_socket',
    parentSocketId: 'left_wrist_socket',
    aliases: ['glove', 'gloves', 'guante', 'guantes'],
    boneHints: ['Hand.L', 'Hand.R'],
  },
  {
    type: 'boots',
    label: 'Botas',
    description: 'Botas o calzado modular.',
    required: false,
    category: 'clothing',
    socketId: 'boot_socket',
    parentSocketId: 'left_ankle_socket',
    aliases: ['boot', 'boots', 'bota', 'botas'],
    boneHints: ['Foot.L', 'Foot.R'],
  },
  {
    type: 'accessory',
    label: 'Accesorio',
    description: 'Pieza suelta adicional.',
    required: false,
    category: 'accessory',
    socketId: 'accessory_socket',
    parentSocketId: 'root',
    aliases: ['accessory', 'accesorio', 'prop', 'gear'],
    boneHints: ['Hand.L', 'Hand.R', 'Head', 'Chest'],
  },
];

export const MODULAR_PART_DEFINITION_MAP = new Map(
  MODULAR_PART_CATALOG.map((entry) => [entry.type, entry])
);
