import * as THREE from 'three';
import type {
  PresetQualityTier,
  PresetRegistryEntry,
} from '@/engine/presets/presetRegistryTypes';

export interface ParticlePresetSeed {
  rate?: number;
  maxParticles?: number;
  burstCount?: number;
  lifetimeMin?: number;
  lifetimeMax?: number;
  shape?: 'point' | 'sphere' | 'cone' | 'box' | 'circle';
  radius?: number;
  angle?: number;
  speedMin?: number;
  speedMax?: number;
  direction?: 'up' | 'down' | 'outward' | 'random' | 'forward';
  inheritVelocity?: number;
  startSizeMin?: number;
  startSizeMax?: number;
  endSizeMin?: number;
  endSizeMax?: number;
  sizeCurve?: 'linear' | 'easeIn' | 'easeOut' | 'bounce';
  startColor?: THREE.Color;
  endColor?: THREE.Color;
  colorCurve?: 'linear' | 'easeIn' | 'easeOut';
  startAlpha?: number;
  endAlpha?: number;
  rotationMin?: number;
  rotationMax?: number;
  angularVelocityMin?: number;
  angularVelocityMax?: number;
  gravity?: number;
  drag?: number;
  bounce?: number;
  blendMode?: 'additive' | 'alpha' | 'multiply' | 'screen';
  texture?: string;
  renderMode?: 'billboard' | 'stretched' | 'horizontal' | 'vertical' | 'mesh';
  sortOrder?: 'oldestFirst' | 'youngestFirst' | 'distance';
  noiseStrength?: number;
  noiseFrequency?: number;
  emitOnWake?: boolean;
  autoDestroy?: boolean;
  destroyWhenEmpty?: boolean;
}

export type ParticlePresetCategory =
  | 'fire'
  | 'smoke'
  | 'magic'
  | 'weather'
  | 'combat'
  | 'environment'
  | 'liquid'
  | 'frost'
  | 'metal'
  | 'shadow';

export interface ParticlePresetRegistryEntry
  extends PresetRegistryEntry<ParticlePresetCategory, ParticlePresetSeed> {
  previewBackend: 'cpu' | 'gpu';
}

interface ParticlePresetEntryInput extends ParticlePresetSeed {
  id: string;
  name: string;
  category: ParticlePresetCategory;
  tags: string[];
  thumbnail?: string;
  qualityTier?: PresetQualityTier;
  previewBackend?: 'cpu' | 'gpu';
}

function createParticlePresetEntry(
  input: ParticlePresetEntryInput
): ParticlePresetRegistryEntry {
  const {
    id,
    name,
    category,
    tags,
    thumbnail = `particle/${id}`,
    qualityTier = 'standard',
    previewBackend = 'cpu',
    ...params
  } = input;

  return {
    id,
    name,
    category,
    tags,
    thumbnail,
    qualityTier,
    previewBackend,
    params,
  };
}

export const PARTICLE_PRESET_CATEGORY_LABELS: Record<ParticlePresetCategory, string> = {
  fire: 'Fire',
  smoke: 'Smoke',
  magic: 'Magic',
  weather: 'Weather',
  combat: 'Combat',
  environment: 'Environment',
  liquid: 'Liquid',
  frost: 'Frost',
  metal: 'Metal',
  shadow: 'Shadow',
};

export const PARTICLE_PRESET_CATEGORY_OPTIONS = (
  Object.entries(PARTICLE_PRESET_CATEGORY_LABELS) as Array<
    [ParticlePresetCategory, string]
  >
).map(([value, label]) => ({ value, label }));

export function getParticlePresetCategoryLabel(category: ParticlePresetCategory) {
  return PARTICLE_PRESET_CATEGORY_LABELS[category];
}

export const PARTICLE_PRESET_REGISTRY: ParticlePresetRegistryEntry[] = [
  createParticlePresetEntry({
    id: 'fire',
    name: 'Fire',
    category: 'fire',
    tags: ['flame', 'embers', 'heat'],
    qualityTier: 'starter',
    rate: 50,
    maxParticles: 500,
    lifetimeMin: 0.5,
    lifetimeMax: 1.5,
    shape: 'circle',
    radius: 0.3,
    speedMin: 2,
    speedMax: 4,
    direction: 'up',
    startSizeMin: 0.3,
    startSizeMax: 0.6,
    endSizeMin: 0,
    endSizeMax: 0.1,
    startColor: new THREE.Color(1, 0.8, 0.2),
    endColor: new THREE.Color(1, 0.1, 0),
    gravity: 0,
    blendMode: 'additive',
  }),
  createParticlePresetEntry({
    id: 'torch_flame',
    name: 'Torch Flame',
    category: 'fire',
    tags: ['torch', 'flame', 'vertical'],
    rate: 36,
    maxParticles: 240,
    lifetimeMin: 0.45,
    lifetimeMax: 1.1,
    shape: 'circle',
    radius: 0.12,
    speedMin: 1.6,
    speedMax: 2.8,
    direction: 'up',
    startSizeMin: 0.18,
    startSizeMax: 0.34,
    endSizeMin: 0,
    endSizeMax: 0.08,
    startColor: new THREE.Color(1, 0.82, 0.28),
    endColor: new THREE.Color(1, 0.25, 0.02),
    gravity: 0.2,
    blendMode: 'additive',
  }),
  createParticlePresetEntry({
    id: 'bonfire',
    name: 'Bonfire',
    category: 'fire',
    tags: ['bonfire', 'campfire', 'embers'],
    qualityTier: 'hero',
    previewBackend: 'gpu',
    rate: 72,
    maxParticles: 700,
    lifetimeMin: 0.6,
    lifetimeMax: 1.8,
    shape: 'circle',
    radius: 0.6,
    speedMin: 2.4,
    speedMax: 5.2,
    direction: 'up',
    startSizeMin: 0.26,
    startSizeMax: 0.52,
    endSizeMin: 0,
    endSizeMax: 0.12,
    startColor: new THREE.Color(1, 0.74, 0.22),
    endColor: new THREE.Color(0.92, 0.1, 0),
    gravity: 0,
    blendMode: 'additive',
    noiseStrength: 0.18,
    noiseFrequency: 1.2,
  }),
  createParticlePresetEntry({
    id: 'embers',
    name: 'Embers',
    category: 'fire',
    tags: ['embers', 'cinders', 'floating'],
    rate: 40,
    maxParticles: 220,
    lifetimeMin: 1.4,
    lifetimeMax: 2.8,
    shape: 'circle',
    radius: 0.45,
    speedMin: 0.5,
    speedMax: 1.4,
    direction: 'up',
    startSizeMin: 0.04,
    startSizeMax: 0.1,
    endSizeMin: 0,
    endSizeMax: 0.03,
    startColor: new THREE.Color(1, 0.52, 0.1),
    endColor: new THREE.Color(0.4, 0.08, 0.02),
    startAlpha: 0.95,
    endAlpha: 0,
    gravity: 0.08,
    blendMode: 'additive',
    noiseStrength: 0.22,
    noiseFrequency: 0.9,
  }),
  createParticlePresetEntry({
    id: 'wildfire_gust',
    name: 'Wildfire Gust',
    category: 'fire',
    tags: ['wildfire', 'wind', 'gust'],
    qualityTier: 'hero',
    previewBackend: 'gpu',
    rate: 90,
    maxParticles: 900,
    lifetimeMin: 0.45,
    lifetimeMax: 1.3,
    shape: 'box',
    radius: 0.9,
    speedMin: 2.4,
    speedMax: 5.4,
    direction: 'forward',
    startSizeMin: 0.16,
    startSizeMax: 0.38,
    endSizeMin: 0,
    endSizeMax: 0.06,
    startColor: new THREE.Color(1, 0.62, 0.16),
    endColor: new THREE.Color(0.82, 0.08, 0.02),
    startAlpha: 0.9,
    endAlpha: 0,
    gravity: -0.2,
    drag: 0.04,
    blendMode: 'additive',
    noiseStrength: 0.5,
    noiseFrequency: 1.6,
  }),
  createParticlePresetEntry({
    id: 'smoke',
    name: 'Smoke',
    category: 'smoke',
    tags: ['smoke', 'vapor', 'soft'],
    qualityTier: 'starter',
    rate: 20,
    maxParticles: 200,
    lifetimeMin: 2,
    lifetimeMax: 4,
    shape: 'circle',
    radius: 0.2,
    speedMin: 0.5,
    speedMax: 1.5,
    direction: 'up',
    startSizeMin: 0.2,
    startSizeMax: 0.4,
    endSizeMin: 1,
    endSizeMax: 2,
    startColor: new THREE.Color(0.3, 0.3, 0.3),
    endColor: new THREE.Color(0.1, 0.1, 0.1),
    startAlpha: 0.8,
    endAlpha: 0,
    gravity: 0.5,
    blendMode: 'alpha',
  }),
  createParticlePresetEntry({
    id: 'black_smoke',
    name: 'Black Smoke',
    category: 'smoke',
    tags: ['smoke', 'dark', 'heavy'],
    rate: 30,
    maxParticles: 280,
    lifetimeMin: 2.4,
    lifetimeMax: 4.8,
    shape: 'circle',
    radius: 0.28,
    speedMin: 0.4,
    speedMax: 1.2,
    direction: 'up',
    startSizeMin: 0.28,
    startSizeMax: 0.5,
    endSizeMin: 1.4,
    endSizeMax: 2.6,
    startColor: new THREE.Color(0.08, 0.08, 0.08),
    endColor: new THREE.Color(0.02, 0.02, 0.02),
    startAlpha: 0.92,
    endAlpha: 0,
    gravity: 0.35,
    drag: 0.05,
    blendMode: 'alpha',
  }),
  createParticlePresetEntry({
    id: 'white_smoke',
    name: 'White Smoke',
    category: 'smoke',
    tags: ['smoke', 'white', 'soft'],
    rate: 26,
    maxParticles: 240,
    lifetimeMin: 1.8,
    lifetimeMax: 3.6,
    shape: 'circle',
    radius: 0.24,
    speedMin: 0.35,
    speedMax: 1.1,
    direction: 'up',
    startSizeMin: 0.22,
    startSizeMax: 0.46,
    endSizeMin: 1.1,
    endSizeMax: 2.1,
    startColor: new THREE.Color(0.92, 0.92, 0.92),
    endColor: new THREE.Color(0.7, 0.7, 0.72),
    startAlpha: 0.72,
    endAlpha: 0,
    gravity: 0.22,
    blendMode: 'alpha',
  }),
  createParticlePresetEntry({
    id: 'steam',
    name: 'Steam',
    category: 'smoke',
    tags: ['steam', 'vapor', 'heat'],
    rate: 34,
    maxParticles: 300,
    lifetimeMin: 1.2,
    lifetimeMax: 2.4,
    shape: 'circle',
    radius: 0.16,
    speedMin: 0.7,
    speedMax: 1.8,
    direction: 'up',
    startSizeMin: 0.18,
    startSizeMax: 0.36,
    endSizeMin: 0.8,
    endSizeMax: 1.6,
    startColor: new THREE.Color(0.88, 0.9, 0.92),
    endColor: new THREE.Color(0.72, 0.76, 0.8),
    startAlpha: 0.52,
    endAlpha: 0,
    gravity: 0.4,
    blendMode: 'alpha',
  }),
  createParticlePresetEntry({
    id: 'ash_fall',
    name: 'Ash Fall',
    category: 'smoke',
    tags: ['ash', 'falling', 'embers'],
    rate: 40,
    maxParticles: 420,
    lifetimeMin: 3.5,
    lifetimeMax: 5.8,
    shape: 'box',
    radius: 2.8,
    speedMin: 0.2,
    speedMax: 0.65,
    direction: 'down',
    startSizeMin: 0.02,
    startSizeMax: 0.08,
    endSizeMin: 0.01,
    endSizeMax: 0.05,
    startColor: new THREE.Color(0.32, 0.3, 0.28),
    endColor: new THREE.Color(0.18, 0.17, 0.16),
    startAlpha: 0.7,
    endAlpha: 0.15,
    gravity: -0.6,
    blendMode: 'alpha',
    noiseStrength: 0.1,
    noiseFrequency: 0.8,
  }),
  createParticlePresetEntry({
    id: 'sparkles',
    name: 'Sparkles',
    category: 'magic',
    tags: ['sparkle', 'glitter', 'ambient'],
    qualityTier: 'starter',
    rate: 100,
    maxParticles: 300,
    lifetimeMin: 0.3,
    lifetimeMax: 0.8,
    shape: 'sphere',
    radius: 0.5,
    speedMin: 1,
    speedMax: 3,
    direction: 'outward',
    startSizeMin: 0.05,
    startSizeMax: 0.15,
    endSizeMin: 0,
    endSizeMax: 0,
    startColor: new THREE.Color(0.5, 0.8, 1),
    endColor: new THREE.Color(1, 1, 1),
    gravity: 0,
    blendMode: 'additive',
  }),
  createParticlePresetEntry({
    id: 'magic',
    name: 'Magic',
    category: 'magic',
    tags: ['magic', 'arcane', 'energy'],
    qualityTier: 'starter',
    rate: 30,
    maxParticles: 150,
    lifetimeMin: 1,
    lifetimeMax: 2,
    shape: 'sphere',
    radius: 0.3,
    speedMin: 0.5,
    speedMax: 2,
    direction: 'random',
    startSizeMin: 0.1,
    startSizeMax: 0.3,
    endSizeMin: 0,
    endSizeMax: 0,
    startColor: new THREE.Color(0.5, 0, 1),
    endColor: new THREE.Color(1, 0, 0.5),
    gravity: 0,
    blendMode: 'additive',
    noiseStrength: 0.5,
  }),
  createParticlePresetEntry({
    id: 'arcane_orbs',
    name: 'Arcane Orbs',
    category: 'magic',
    tags: ['orbs', 'arcane', 'floating'],
    qualityTier: 'hero',
    rate: 18,
    maxParticles: 120,
    lifetimeMin: 1.8,
    lifetimeMax: 3.2,
    shape: 'sphere',
    radius: 0.45,
    speedMin: 0.15,
    speedMax: 0.6,
    direction: 'random',
    startSizeMin: 0.12,
    startSizeMax: 0.24,
    endSizeMin: 0.04,
    endSizeMax: 0.1,
    startColor: new THREE.Color(0.26, 0.72, 1),
    endColor: new THREE.Color(0.9, 0.28, 1),
    startAlpha: 0.9,
    endAlpha: 0,
    gravity: 0,
    drag: 0.08,
    blendMode: 'additive',
    noiseStrength: 0.4,
    noiseFrequency: 1.1,
  }),
  createParticlePresetEntry({
    id: 'fairy_dust',
    name: 'Fairy Dust',
    category: 'magic',
    tags: ['fairy', 'dust', 'float'],
    rate: 60,
    maxParticles: 260,
    lifetimeMin: 1.1,
    lifetimeMax: 2.2,
    shape: 'sphere',
    radius: 0.55,
    speedMin: 0.15,
    speedMax: 0.8,
    direction: 'random',
    startSizeMin: 0.03,
    startSizeMax: 0.08,
    endSizeMin: 0,
    endSizeMax: 0.03,
    startColor: new THREE.Color(1, 0.86, 0.52),
    endColor: new THREE.Color(1, 0.55, 0.88),
    startAlpha: 0.95,
    endAlpha: 0,
    gravity: 0,
    drag: 0.08,
    blendMode: 'additive',
  }),
  createParticlePresetEntry({
    id: 'gold_glitter',
    name: 'Gold Glitter',
    category: 'magic',
    tags: ['gold', 'glitter', 'luxury'],
    qualityTier: 'hero',
    rate: 48,
    maxParticles: 240,
    lifetimeMin: 0.8,
    lifetimeMax: 1.8,
    shape: 'sphere',
    radius: 0.4,
    speedMin: 0.25,
    speedMax: 1.2,
    direction: 'outward',
    startSizeMin: 0.03,
    startSizeMax: 0.1,
    endSizeMin: 0,
    endSizeMax: 0.03,
    startColor: new THREE.Color(1, 0.82, 0.22),
    endColor: new THREE.Color(0.72, 0.46, 0.02),
    startAlpha: 0.92,
    endAlpha: 0,
    gravity: -0.1,
    blendMode: 'additive',
  }),
  createParticlePresetEntry({
    id: 'snow',
    name: 'Snow',
    category: 'weather',
    tags: ['snow', 'winter', 'falling'],
    qualityTier: 'starter',
    rate: 50,
    maxParticles: 1000,
    lifetimeMin: 5,
    lifetimeMax: 10,
    shape: 'box',
    radius: 10,
    speedMin: 0.5,
    speedMax: 1,
    direction: 'down',
    startSizeMin: 0.05,
    startSizeMax: 0.15,
    endSizeMin: 0.05,
    endSizeMax: 0.15,
    startColor: new THREE.Color(1, 1, 1),
    endColor: new THREE.Color(0.9, 0.9, 1),
    startAlpha: 0.8,
    endAlpha: 0.3,
    gravity: -2,
    blendMode: 'alpha',
  }),
  createParticlePresetEntry({
    id: 'rain',
    name: 'Rain',
    category: 'weather',
    tags: ['rain', 'storm', 'falling'],
    qualityTier: 'hero',
    previewBackend: 'gpu',
    rate: 140,
    maxParticles: 1400,
    lifetimeMin: 1.2,
    lifetimeMax: 2,
    shape: 'box',
    radius: 6,
    speedMin: 6,
    speedMax: 11,
    direction: 'down',
    startSizeMin: 0.02,
    startSizeMax: 0.04,
    endSizeMin: 0.02,
    endSizeMax: 0.04,
    startColor: new THREE.Color(0.7, 0.82, 1),
    endColor: new THREE.Color(0.5, 0.7, 0.96),
    startAlpha: 0.48,
    endAlpha: 0.18,
    gravity: -12,
    drag: 0.01,
    blendMode: 'alpha',
    renderMode: 'stretched',
  }),
  createParticlePresetEntry({
    id: 'blizzard',
    name: 'Blizzard',
    category: 'weather',
    tags: ['snow', 'blizzard', 'wind'],
    qualityTier: 'hero',
    previewBackend: 'gpu',
    rate: 120,
    maxParticles: 1200,
    lifetimeMin: 2.4,
    lifetimeMax: 4.2,
    shape: 'box',
    radius: 5.5,
    speedMin: 1.4,
    speedMax: 3.8,
    direction: 'forward',
    startSizeMin: 0.04,
    startSizeMax: 0.14,
    endSizeMin: 0.03,
    endSizeMax: 0.12,
    startColor: new THREE.Color(0.96, 0.98, 1),
    endColor: new THREE.Color(0.78, 0.84, 0.96),
    startAlpha: 0.9,
    endAlpha: 0.25,
    gravity: -2.5,
    drag: 0.08,
    blendMode: 'alpha',
    noiseStrength: 0.5,
    noiseFrequency: 1.4,
  }),
  createParticlePresetEntry({
    id: 'mist',
    name: 'Mist',
    category: 'weather',
    tags: ['mist', 'fog', 'ambient'],
    rate: 24,
    previewBackend: 'gpu',
    maxParticles: 220,
    lifetimeMin: 3.4,
    lifetimeMax: 5.5,
    shape: 'box',
    radius: 1.8,
    speedMin: 0.05,
    speedMax: 0.22,
    direction: 'random',
    startSizeMin: 0.8,
    startSizeMax: 1.4,
    endSizeMin: 1.6,
    endSizeMax: 2.4,
    startColor: new THREE.Color(0.82, 0.86, 0.9),
    endColor: new THREE.Color(0.7, 0.76, 0.84),
    startAlpha: 0.22,
    endAlpha: 0,
    gravity: 0,
    drag: 0.18,
    blendMode: 'alpha',
  }),
  createParticlePresetEntry({
    id: 'blood',
    name: 'Blood',
    category: 'combat',
    tags: ['blood', 'hit', 'spray'],
    qualityTier: 'starter',
    burstCount: 20,
    rate: 0,
    maxParticles: 50,
    lifetimeMin: 0.5,
    lifetimeMax: 1,
    shape: 'point',
    radius: 0,
    speedMin: 3,
    speedMax: 8,
    direction: 'outward',
    startSizeMin: 0.1,
    startSizeMax: 0.3,
    endSizeMin: 0.05,
    endSizeMax: 0.1,
    startColor: new THREE.Color(0.8, 0, 0),
    endColor: new THREE.Color(0.4, 0, 0),
    gravity: -15,
    blendMode: 'alpha',
  }),
  createParticlePresetEntry({
    id: 'explosion',
    name: 'Explosion',
    category: 'combat',
    tags: ['explosion', 'burst', 'impact'],
    qualityTier: 'starter',
    burstCount: 100,
    rate: 0,
    maxParticles: 200,
    lifetimeMin: 0.5,
    lifetimeMax: 1.5,
    shape: 'point',
    radius: 0,
    speedMin: 5,
    speedMax: 15,
    direction: 'outward',
    startSizeMin: 0.2,
    startSizeMax: 0.5,
    endSizeMin: 0,
    endSizeMax: 0,
    startColor: new THREE.Color(1, 0.5, 0),
    endColor: new THREE.Color(1, 0.1, 0),
    gravity: -5,
    blendMode: 'additive',
    autoDestroy: true,
  }),
  createParticlePresetEntry({
    id: 'impact_sparks',
    name: 'Impact Sparks',
    category: 'combat',
    tags: ['impact', 'sparks', 'hit'],
    burstCount: 32,
    rate: 0,
    maxParticles: 90,
    lifetimeMin: 0.18,
    lifetimeMax: 0.55,
    shape: 'point',
    radius: 0,
    speedMin: 4,
    speedMax: 11,
    direction: 'outward',
    startSizeMin: 0.04,
    startSizeMax: 0.12,
    endSizeMin: 0,
    endSizeMax: 0.02,
    startColor: new THREE.Color(1, 0.9, 0.48),
    endColor: new THREE.Color(1, 0.32, 0.04),
    gravity: -6,
    drag: 0.03,
    blendMode: 'additive',
  }),
  createParticlePresetEntry({
    id: 'toxic_cloud',
    name: 'Toxic Cloud',
    category: 'combat',
    tags: ['toxic', 'poison', 'acid'],
    qualityTier: 'hero',
    rate: 22,
    maxParticles: 240,
    lifetimeMin: 2.2,
    lifetimeMax: 4.4,
    shape: 'sphere',
    radius: 0.5,
    speedMin: 0.12,
    speedMax: 0.55,
    direction: 'random',
    startSizeMin: 0.28,
    startSizeMax: 0.48,
    endSizeMin: 1.1,
    endSizeMax: 2.2,
    startColor: new THREE.Color(0.42, 0.92, 0.18),
    endColor: new THREE.Color(0.18, 0.42, 0.04),
    startAlpha: 0.66,
    endAlpha: 0,
    gravity: 0.08,
    blendMode: 'alpha',
    noiseStrength: 0.18,
    noiseFrequency: 0.9,
  }),
  createParticlePresetEntry({
    id: 'dust',
    name: 'Dust',
    category: 'environment',
    tags: ['dust', 'ambient', 'debris'],
    qualityTier: 'starter',
    rate: 10,
    maxParticles: 100,
    lifetimeMin: 2,
    lifetimeMax: 4,
    shape: 'box',
    radius: 2,
    speedMin: 0.1,
    speedMax: 0.5,
    direction: 'random',
    startSizeMin: 0.05,
    startSizeMax: 0.2,
    endSizeMin: 0.05,
    endSizeMax: 0.2,
    startColor: new THREE.Color(0.6, 0.5, 0.4),
    endColor: new THREE.Color(0.4, 0.3, 0.2),
    startAlpha: 0.5,
    endAlpha: 0,
    gravity: 0,
    blendMode: 'alpha',
  }),
  createParticlePresetEntry({
    id: 'sand_swirl',
    name: 'Sand Swirl',
    category: 'environment',
    tags: ['sand', 'desert', 'swirl'],
    rate: 34,
    maxParticles: 280,
    lifetimeMin: 1.8,
    lifetimeMax: 3.2,
    shape: 'sphere',
    radius: 0.9,
    speedMin: 0.5,
    speedMax: 1.8,
    direction: 'random',
    startSizeMin: 0.06,
    startSizeMax: 0.18,
    endSizeMin: 0.04,
    endSizeMax: 0.12,
    startColor: new THREE.Color(0.82, 0.72, 0.45),
    endColor: new THREE.Color(0.58, 0.46, 0.22),
    startAlpha: 0.62,
    endAlpha: 0,
    gravity: -0.2,
    drag: 0.08,
    blendMode: 'alpha',
    noiseStrength: 0.3,
    noiseFrequency: 1.2,
  }),
  createParticlePresetEntry({
    id: 'gravel_burst',
    name: 'Gravel Burst',
    category: 'environment',
    tags: ['gravel', 'rock', 'burst'],
    burstCount: 26,
    rate: 0,
    maxParticles: 80,
    lifetimeMin: 0.55,
    lifetimeMax: 1.3,
    shape: 'point',
    radius: 0,
    speedMin: 2.2,
    speedMax: 6.5,
    direction: 'outward',
    startSizeMin: 0.08,
    startSizeMax: 0.2,
    endSizeMin: 0.02,
    endSizeMax: 0.08,
    startColor: new THREE.Color(0.5, 0.48, 0.44),
    endColor: new THREE.Color(0.26, 0.24, 0.2),
    startAlpha: 0.86,
    endAlpha: 0,
    gravity: -9.5,
    drag: 0.02,
    blendMode: 'alpha',
  }),
  createParticlePresetEntry({
    id: 'leaf_drift',
    name: 'Leaf Drift',
    category: 'environment',
    tags: ['leaf', 'autumn', 'drift'],
    rate: 20,
    maxParticles: 160,
    lifetimeMin: 2.8,
    lifetimeMax: 5.2,
    shape: 'box',
    radius: 2.4,
    speedMin: 0.15,
    speedMax: 0.9,
    direction: 'random',
    startSizeMin: 0.1,
    startSizeMax: 0.22,
    endSizeMin: 0.08,
    endSizeMax: 0.16,
    startColor: new THREE.Color(0.9, 0.48, 0.1),
    endColor: new THREE.Color(0.46, 0.21, 0.06),
    startAlpha: 0.72,
    endAlpha: 0.16,
    gravity: -0.8,
    drag: 0.12,
    blendMode: 'alpha',
    noiseStrength: 0.36,
    noiseFrequency: 0.7,
  }),
  createParticlePresetEntry({
    id: 'ambient_motes',
    name: 'Ambient Motes',
    category: 'environment',
    tags: ['ambient', 'float', 'dust'],
    qualityTier: 'hero',
    rate: 26,
    maxParticles: 200,
    lifetimeMin: 3.8,
    lifetimeMax: 7,
    shape: 'box',
    radius: 1.6,
    speedMin: 0.02,
    speedMax: 0.18,
    direction: 'random',
    startSizeMin: 0.02,
    startSizeMax: 0.06,
    endSizeMin: 0.01,
    endSizeMax: 0.03,
    startColor: new THREE.Color(1, 0.95, 0.78),
    endColor: new THREE.Color(0.72, 0.68, 0.58),
    startAlpha: 0.34,
    endAlpha: 0,
    gravity: 0,
    drag: 0.2,
    blendMode: 'additive',
  }),
  createParticlePresetEntry({
    id: 'water_splash',
    name: 'Water Splash',
    category: 'liquid',
    tags: ['water', 'splash', 'impact'],
    qualityTier: 'hero',
    burstCount: 48,
    rate: 0,
    maxParticles: 120,
    lifetimeMin: 0.4,
    lifetimeMax: 1.1,
    shape: 'point',
    radius: 0,
    speedMin: 2.4,
    speedMax: 7.2,
    direction: 'outward',
    startSizeMin: 0.06,
    startSizeMax: 0.16,
    endSizeMin: 0.02,
    endSizeMax: 0.08,
    startColor: new THREE.Color(0.72, 0.88, 1),
    endColor: new THREE.Color(0.28, 0.56, 0.92),
    startAlpha: 0.7,
    endAlpha: 0,
    gravity: -8,
    drag: 0.04,
    blendMode: 'alpha',
  }),
  createParticlePresetEntry({
    id: 'waterfall_spray',
    name: 'Waterfall Spray',
    category: 'liquid',
    tags: ['waterfall', 'spray', 'mist'],
    qualityTier: 'hero',
    previewBackend: 'gpu',
    rate: 86,
    maxParticles: 720,
    lifetimeMin: 0.9,
    lifetimeMax: 1.8,
    shape: 'box',
    radius: 1.2,
    speedMin: 1.2,
    speedMax: 3.1,
    direction: 'down',
    startSizeMin: 0.08,
    startSizeMax: 0.18,
    endSizeMin: 0.1,
    endSizeMax: 0.32,
    startColor: new THREE.Color(0.84, 0.94, 1),
    endColor: new THREE.Color(0.62, 0.8, 0.96),
    startAlpha: 0.6,
    endAlpha: 0,
    gravity: -3.5,
    drag: 0.05,
    blendMode: 'alpha',
  }),
  createParticlePresetEntry({
    id: 'bubble_trail',
    name: 'Bubble Trail',
    category: 'liquid',
    tags: ['bubble', 'underwater', 'trail'],
    rate: 28,
    maxParticles: 180,
    lifetimeMin: 1.2,
    lifetimeMax: 2.4,
    shape: 'circle',
    radius: 0.2,
    speedMin: 0.18,
    speedMax: 0.6,
    direction: 'up',
    startSizeMin: 0.03,
    startSizeMax: 0.1,
    endSizeMin: 0.05,
    endSizeMax: 0.12,
    startColor: new THREE.Color(0.88, 0.96, 1),
    endColor: new THREE.Color(0.72, 0.88, 1),
    startAlpha: 0.42,
    endAlpha: 0,
    gravity: 0.6,
    drag: 0.04,
    blendMode: 'alpha',
  }),
  createParticlePresetEntry({
    id: 'mercury_droplets',
    name: 'Mercury Droplets',
    category: 'liquid',
    tags: ['mercury', 'liquid-metal', 'droplets'],
    qualityTier: 'hero',
    burstCount: 22,
    rate: 0,
    maxParticles: 70,
    lifetimeMin: 0.8,
    lifetimeMax: 1.8,
    shape: 'point',
    radius: 0,
    speedMin: 1.2,
    speedMax: 3.8,
    direction: 'outward',
    startSizeMin: 0.05,
    startSizeMax: 0.14,
    endSizeMin: 0.02,
    endSizeMax: 0.08,
    startColor: new THREE.Color(0.86, 0.88, 0.92),
    endColor: new THREE.Color(0.4, 0.42, 0.46),
    startAlpha: 0.94,
    endAlpha: 0,
    gravity: -9.8,
    drag: 0.02,
    blendMode: 'alpha',
  }),
  createParticlePresetEntry({
    id: 'ice_shards',
    name: 'Ice Shards',
    category: 'frost',
    tags: ['ice', 'shards', 'freeze'],
    qualityTier: 'hero',
    burstCount: 40,
    rate: 0,
    maxParticles: 100,
    lifetimeMin: 0.5,
    lifetimeMax: 1.3,
    shape: 'point',
    radius: 0,
    speedMin: 2.2,
    speedMax: 6.4,
    direction: 'outward',
    startSizeMin: 0.05,
    startSizeMax: 0.16,
    endSizeMin: 0.01,
    endSizeMax: 0.05,
    startColor: new THREE.Color(0.84, 0.96, 1),
    endColor: new THREE.Color(0.4, 0.7, 0.96),
    startAlpha: 0.86,
    endAlpha: 0,
    gravity: -7.8,
    drag: 0.02,
    blendMode: 'additive',
  }),
  createParticlePresetEntry({
    id: 'freezing_mist',
    name: 'Freezing Mist',
    category: 'frost',
    tags: ['freeze', 'mist', 'cold'],
    qualityTier: 'hero',
    rate: 28,
    maxParticles: 260,
    lifetimeMin: 1.8,
    lifetimeMax: 3.5,
    shape: 'sphere',
    radius: 0.45,
    speedMin: 0.12,
    speedMax: 0.48,
    direction: 'random',
    startSizeMin: 0.2,
    startSizeMax: 0.4,
    endSizeMin: 0.9,
    endSizeMax: 1.8,
    startColor: new THREE.Color(0.82, 0.96, 1),
    endColor: new THREE.Color(0.54, 0.78, 0.96),
    startAlpha: 0.48,
    endAlpha: 0,
    gravity: -0.12,
    drag: 0.15,
    blendMode: 'alpha',
  }),
  createParticlePresetEntry({
    id: 'grinder_sparks',
    name: 'Grinder Sparks',
    category: 'metal',
    tags: ['metal', 'grinder', 'sparks'],
    qualityTier: 'hero',
    burstCount: 30,
    rate: 0,
    maxParticles: 90,
    lifetimeMin: 0.2,
    lifetimeMax: 0.6,
    shape: 'cone',
    radius: 0.12,
    speedMin: 4.5,
    speedMax: 10.5,
    direction: 'forward',
    startSizeMin: 0.03,
    startSizeMax: 0.08,
    endSizeMin: 0,
    endSizeMax: 0.02,
    startColor: new THREE.Color(1, 0.94, 0.7),
    endColor: new THREE.Color(1, 0.4, 0.06),
    startAlpha: 1,
    endAlpha: 0,
    gravity: -6,
    drag: 0.02,
    blendMode: 'additive',
  }),
  createParticlePresetEntry({
    id: 'molten_metal',
    name: 'Molten Metal',
    category: 'metal',
    tags: ['molten', 'metal', 'spray'],
    qualityTier: 'hero',
    rate: 22,
    maxParticles: 180,
    lifetimeMin: 0.5,
    lifetimeMax: 1.2,
    shape: 'circle',
    radius: 0.18,
    speedMin: 1.6,
    speedMax: 3.4,
    direction: 'up',
    startSizeMin: 0.06,
    startSizeMax: 0.18,
    endSizeMin: 0.01,
    endSizeMax: 0.05,
    startColor: new THREE.Color(1, 0.56, 0.1),
    endColor: new THREE.Color(0.52, 0.08, 0.02),
    startAlpha: 0.88,
    endAlpha: 0,
    gravity: -5.5,
    drag: 0.03,
    blendMode: 'additive',
  }),
  createParticlePresetEntry({
    id: 'chrome_dust',
    name: 'Chrome Dust',
    category: 'metal',
    tags: ['chrome', 'dust', 'metallic'],
    rate: 18,
    maxParticles: 160,
    lifetimeMin: 1.4,
    lifetimeMax: 2.8,
    shape: 'box',
    radius: 0.8,
    speedMin: 0.08,
    speedMax: 0.34,
    direction: 'random',
    startSizeMin: 0.03,
    startSizeMax: 0.08,
    endSizeMin: 0.01,
    endSizeMax: 0.03,
    startColor: new THREE.Color(0.86, 0.9, 0.95),
    endColor: new THREE.Color(0.42, 0.46, 0.52),
    startAlpha: 0.44,
    endAlpha: 0,
    gravity: 0,
    drag: 0.12,
    blendMode: 'alpha',
  }),
  createParticlePresetEntry({
    id: 'void_smoke',
    name: 'Void Smoke',
    category: 'shadow',
    tags: ['void', 'shadow', 'dark'],
    qualityTier: 'hero',
    previewBackend: 'gpu',
    rate: 26,
    maxParticles: 260,
    lifetimeMin: 2.2,
    lifetimeMax: 4.5,
    shape: 'sphere',
    radius: 0.45,
    speedMin: 0.08,
    speedMax: 0.4,
    direction: 'random',
    startSizeMin: 0.26,
    startSizeMax: 0.48,
    endSizeMin: 1,
    endSizeMax: 2,
    startColor: new THREE.Color(0.08, 0.02, 0.12),
    endColor: new THREE.Color(0.01, 0.01, 0.02),
    startAlpha: 0.62,
    endAlpha: 0,
    gravity: -0.05,
    drag: 0.08,
    blendMode: 'alpha',
    noiseStrength: 0.4,
    noiseFrequency: 0.9,
  }),
  createParticlePresetEntry({
    id: 'shadow_motes',
    name: 'Shadow Motes',
    category: 'shadow',
    tags: ['shadow', 'motes', 'ambient'],
    rate: 36,
    maxParticles: 180,
    lifetimeMin: 2.6,
    lifetimeMax: 4.8,
    shape: 'sphere',
    radius: 0.55,
    speedMin: 0.03,
    speedMax: 0.18,
    direction: 'random',
    startSizeMin: 0.04,
    startSizeMax: 0.12,
    endSizeMin: 0.01,
    endSizeMax: 0.04,
    startColor: new THREE.Color(0.18, 0.02, 0.26),
    endColor: new THREE.Color(0.02, 0.02, 0.04),
    startAlpha: 0.5,
    endAlpha: 0,
    gravity: 0,
    drag: 0.14,
    blendMode: 'additive',
  }),
  createParticlePresetEntry({
    id: 'dark_flare',
    name: 'Dark Flare',
    category: 'shadow',
    tags: ['dark', 'flare', 'burst'],
    qualityTier: 'hero',
    burstCount: 18,
    rate: 0,
    maxParticles: 70,
    lifetimeMin: 0.45,
    lifetimeMax: 1,
    shape: 'point',
    radius: 0,
    speedMin: 1.5,
    speedMax: 4.8,
    direction: 'outward',
    startSizeMin: 0.08,
    startSizeMax: 0.18,
    endSizeMin: 0.01,
    endSizeMax: 0.04,
    startColor: new THREE.Color(0.42, 0.08, 0.7),
    endColor: new THREE.Color(0.04, 0.02, 0.08),
    startAlpha: 0.9,
    endAlpha: 0,
    gravity: -0.5,
    drag: 0.03,
    blendMode: 'additive',
  }),
];

export type ParticlePresetId = string;

export const PARTICLE_PRESET_REGISTRY_MAP = new Map(
  PARTICLE_PRESET_REGISTRY.map((entry) => [entry.id, entry] as const)
);

export function getParticlePresetRegistryEntry(presetId: string | null | undefined) {
  if (!presetId) {
    return null;
  }
  return PARTICLE_PRESET_REGISTRY_MAP.get(presetId) ?? null;
}

export const MIN_PARTICLE_PRESET_REGISTRY_COUNT = 36;
